---
- name: Install Docker
  hosts: all
  # gather_facts: no
  collections:   # Define collections to search
    - community.docker
  

- name: Install Docker-Compose
  hosts: all
  # gather_facts: no
  roles:
    - role: andrewrothstein.docker-compose
      become: true
  